name: release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build-pack-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: "@djbf"
          cache: "npm"

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            echo "No package-lock.json found; using npm install"
            npm install --include=dev --ignore-scripts
          fi

      - name: Build (TypeScript)
        run: npm run build

      - name: Sanity check dist
        run: test -f dist/cli.js

      - name: Verify tag matches package.json version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          PKG="$(node -p -e "require('./package.json').version")"
          echo "Tag: $TAG, package.json: $PKG"
          [ "$TAG" = "$PKG" ] || { echo "Version mismatch"; exit 1; }

      - name: Create tarball (artifact)
        run: npm pack

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: traceweave-tarball
          path: ./*.tgz
          if-no-files-found: error

      - name: Publish to GitHub Packages
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
